### ISSUE TITLE
Questions: Flavors with firebase, debug and select flavor in my IDE

### ISSUE THREAD

**Issue by wemersonrv** [lrferreiro/flutter_flavor#1]
Hello.

Great package. I've install it here and test. just *A.M.A.Z.I.N.G.!!!!!*

I've used flutter with flavors before, but manually. This plugin oversimplifies the process!

But, i have some questions:

**1. Firebase auth, firestore, etc.**
How to configure firebase to use differente flavors

**2. Debug breakpoints**
There is a way to debug, create breakpoints, etc?

**3. IDE**
There is a way to configure VSCode or Android Studio to select the flavor when making the build?

**Comment by danielwalczak** [comment]
did you solve the issue ?

**Comment by lrferreiro** [comment]
Hello
Sorry for the delay in responding.
The plugin has not been tested yet configuring firebase auth, firestore, etc. I keep it in mind for the next update.
It is also possible to configure VSCode and Visual Studio, in the next update I will incorporate a configuration example.
Thank you!!

**Comment by lrferreiro** [comment]
Hi.
**1-** The configuration on firebase has not been tested.
**2-** Several tests were done on the latest version of the plugin and in debug mode, it does stop at break points. The tests were done in VSCode. If it is possible to share some small code example to be able to review and test it would be nice, but the various tests that were done all went well.
**3-** The documentation shows how to configure different flavors in VSCode.
Thank's
