### ISSUE TITLE
Update the xml dependency to version 6.x.x

### ISSUE THREAD

**Issue by jakub-cosmose** [lrferreiro/flutter_flavor#13]
The project currently depends on `xml: ^5.1.2`, what makes it impossible to use together with other libraries that depend on the newer (6.x.x) versions of `xml`.
#11

**Comment by mohanadshaban** [comment]
Yes Please +++

**Comment by dragouf** [comment]
I can't use last version of flutter_svg because of that ...

**Comment by lrferreiro** [comment]
Updated to flutter 3
