### ISSUE TITLE
how to flutter web flavor in index.html

### ISSUE THREAD

**Issue by hiteshsapra** [lrferreiro/flutter_flavor#15]
I'm trying to different flavor for the flutter web index.html files.
index_dev.html
index_prod.html
But it's not working. 

[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mac-19/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (6 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

**Comment by lrferreiro** [comment]
Hello

The first thing you need to do is configure the .vscode:
The .vscode folder is created in the workspace, if it does not exist it can be created by hand. Inside that folder a launch.json file is created and the configuration is established inside the file. For more information, visit: [https://code.visualstudio.com/docs/editor/debugging and https://go.microsoft.com/fwlink/?linkid=830387](url)

<img width="317" alt="Captura de pantalla 2023-01-04 a las 12 34 12 p m" src="https://user-images.githubusercontent.com/23462277/210615370-cf07cdcc-c99f-4652-b81d-b9518fc4a3b1.png">

<img width="379" alt="Captura de pantalla 2023-01-04 a las 12 35 28 p m" src="https://user-images.githubusercontent.com/23462277/210615599-20ba413b-d3bc-4eed-b504-08d0a21ea2aa.png">

Then you can continue with the FlavorConfig as it comes in the documentation, and when you go to run the app then select the flavor you want.

**In main.dart file**

`FlavorConfig(
    location: BannerLocation.bottomStart,
    variables: {
        "counter": 0,
        "baseUrl": "https://www.example-pro.com",
    }
);`

**In main_dev.dart file**

`FlavorConfig(
    name: "DEVELOP",
    color: Colors.red,
    location: BannerLocation.bottomStart,
    variables: {
        "counter": 0,
        "baseUrl": "https://www.example-dev.com",
    }
);`

**Access to variables**

`FlavorConfig.instance.variables["counter"]`

**Comment by lrferreiro** [comment]
<img width="317" alt="Captura de pantalla 2023-01-04 a las 12 34 12 p m" src="https://user-images.githubusercontent.com/23462277/210615370-cf07cdcc-c99f-4652-b81d-b9518fc4a3b1.png">

<img width="379" alt="Captura de pantalla 2023-01-04 a las 12 35 28 p m" src="https://user-images.githubusercontent.com/23462277/210615599-20ba413b-d3bc-4eed-b504-08d0a21ea2aa.png">

**Comment by 9series-flutter** [comment]
> Hello
> 
> The first thing you need to do is configure the .vscode: The .vscode folder is created in the workspace, if it does not exist it can be created by hand. Inside that folder a launch.json file is created and the configuration is established inside the file. For more information, visit: [https://code.visualstudio.com/docs/editor/debugging and https://go.microsoft.com/fwlink/?linkid=830387](url)
> 
> <img alt="Captura de pantalla 2023-01-04 a las 12 34 12 p m" width="317" src="https://user-images.githubusercontent.com/23462277/210615370-cf07cdcc-c99f-4652-b81d-b9518fc4a3b1.png">
> 
> <img alt="Captura de pantalla 2023-01-04 a las 12 35 28 p m" width="379" src="https://user-images.githubusercontent.com/23462277/210615599-20ba413b-d3bc-4eed-b504-08d0a21ea2aa.png">
> 
> Then you can continue with the FlavorConfig as it comes in the documentation, and when you go to run the app then select the flavor you want.
> 
> **In main.dart file**
> 
> `FlavorConfig( location: BannerLocation.bottomStart, variables: { "counter": 0, "baseUrl": "https://www.example-pro.com", } );`
> 
> **In main_dev.dart file**
> 
> `FlavorConfig( name: "DEVELOP", color: Colors.red, location: BannerLocation.bottomStart, variables: { "counter": 0, "baseUrl": "https://www.example-dev.com", } );`
> 
> **Access to variables**
> 
> `FlavorConfig.instance.variables["counter"]`

Thank you for answering. But this is not a solution for the index.html file, We are already using this flavor config, it doesn't provide flavor in the index.html file. We want a solution for using index.html and index_dev.html.

**Comment by lrferreiro** [comment]
For native flavor there is a package [https://pub.dev/packages/flutter_flavorizr](https://pub.dev/packages/flutter_flavorizr). But it has nothing web. So it's time to implement your package yourself. Thank you, I hope you can solve it.

**Comment by saprahits** [comment]
> For native flavor there is a package https://pub.dev/packages/flutter_flavorizr. But it has nothing web. So it's time to implement your package yourself. Thank you, I hope you can solve it.

I don't know why @lrferreiro does not understand my question. My question Re: Flutter Web. 
And @lrferreiro this plugin is not support flutter web [](https://pub.dev/packages/flutter_flavorizr)

And @lrferreiro you guys without solving the issue how closed??????
