### ISSUE TITLE
[ Entry point(s) & Flavorising classes ]

### ISSUE THREAD

**Issue by Gobmichet** [lrferreiro/flutter_flavor#17]
Hi,
Thanks for the job,

1/
i've read many tutorials on the subject including the official flutter doc and i have to admit i'm quite confused with having to create as many entry points as flavors...
That is to say one main.dart per Flavor indeed...

Isn't there a way to have an only entry point ?

I thought that it would work like this :
- Entry point = main.dart
- When entering main.dart, test the --flavor <flavor> param of the executed cmd line
- switch() on that <flavor> then load correct params...

what's the point of --flavor <Flavor> then ? can't we just precise the entry point and have the exact same behavior without the whole flavor configuration stuff ??

2/
I already got a config.dart file where i got all my project's URLs in a Config class.
> **But NO base_url in common :( Since there are 30+ URLs how to correctly Flavorise them ??**

is there a way to flavorise whole classes ?
For example, can i just write something like :
```
FlavorConfig(
    name: "DEVELOP",
    color: Colors.red,
    location: BannerLocation.bottomStart,
    variables: {
        "counter": 0,
         ̶ ̶"̶b̶a̶s̶e̶U̶r̶l̶"̶:̶ ̶"̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶e̶x̶a̶m̶p̶l̶e̶.̶c̶o̶m̶"̶,̶
    }
    **config : ConfigDev** // or Config if --flavor prod
);
```
and then use it in my code like
`FlutterConfig.instance.config.urlWanted`
with 
```
class Config {
  static const String urlWanted = "https://prod-dummy-ws/api/";
  [...]
}
```
Would that work ?

3/ 
Last but not least, how do you launch the different flavors ?
I mean for the moment i created a different config in Android Studio but what is the lib "way" to launch the different flavors ? i can't find any cmd line to launch on the pub.dev lib's page ?
Android ?
iOS ?

I'm quite confused here,
Can u help plz ?

**Comment by lrferreiro** [comment]
Hello, sorry for the delay, --flavor is for native flavors, in this case this package is not for native flavors, so you don't have to configure anything on Android or iOS. For native use there is another package that I mention in the documentation of this package.

The different entries are launched with -t, example: flutter run -t lib/dev_main.dart or you can also use the IDE.

Thanks for asking. I hope my answer is helpful to you.
