### ISSUE TITLE
When use flavor, debug not works. Do not stop on breakpoints

### ISSUE THREAD

**Issue by wemersonrv** [lrferreiro/flutter_flavor#2]
Hi.

Plugin is working fine and its working with flavors right. But, i cannot debug my code because it doesn't stop at any break point.

Using the 3 flavors. and all of them runs fine. but no one of them allows debug.

**Comment by lrferreiro** [comment]
Hi.
Several tests were done on the latest version of the plugin and in debug mode, it does stop at break points. The tests were done in VSCode. If it is possible to share some small code example to be able to review and test it would be nice, but the various tests that were done all went well.
