### ISSUE TITLE
Flavor banner not showing 

### ISSUE THREAD

**Issue by alvindrakes** [lrferreiro/flutter_flavor#5]
I have set the 'name', 'color' and 'location' of the FlavorConfig (as per README.md) , 

> Note By default the banner is shown in BannerLocation.topStart and is visibility only when the attribute name of configuration is defined and not empty.

But the flavor banner does not show at all for all flavors. 

Code sample: 

```
void main() async {
  FlavorConfig(
    name: "Stg",
    location: BannerLocation.bottomStart,
    color: Colors.yellow,
    variables: {
      "environment": AppEnvironment.staging,
      "initializeCrashlytics": true,
    },
  );

  return AppConfig.createApp();
}

```

- Flutter version: 1.22.4
- package version: ^1.1.3

**Comment by ThiagoBfim** [comment]
You must include FlavorBanner Widget.

Like this:

```
void main() async {
  FlavorConfig(
    name: "Stg",
    location: BannerLocation.bottomStart,
    color: Colors.yellow,
    variables: {
      "environment": AppEnvironment.staging,
      "initializeCrashlytics": true,
    },
  );

  return FlavorBanner(child: AppConfig.createApp());
}
```

**Comment by alvindrakes** [comment]
@ThiagoBfim  Thank you! Didn't notice it from the doc. Maybe update the code example to include `FlavorBanner` =)
